export const MAX_WEAPONS = 6;
export const WORLD = 2400;
export const SEASONS = [
  {
    name: "봄",
    en: "SPRING",
    color: "#c6e886",
    sub: "다시, 숲으로",
    enemy: "뱀",
  },
  {
    name: "여름",
    en: "SUMMER",
    color: "#f0d373",
    sub: "짙어지는 녹음",
    enemy: "여우",
  },
  {
    name: "가을",
    en: "AUTUMN",
    color: "#eda45f",
    sub: "낙엽 아래의 흔적",
    enemy: "멧돼지",
  },
  {
    name: "겨울",
    en: "WINTER",
    color: "#b6ddea",
    sub: "긴 겨울의 그림자",
    enemy: "겨울곰",
  },
];
const levels = (base, changes) =>
  changes.reduce((a, p) => [...a, { ...a.at(-1), ...p }], [base]);
export const WEAPONS = [
  {
    id: "acorn",
    name: "도토리 새총",
    glyph: "↗",
    color: "#e9bb68",
    tag: "원거리 · 관통",
    desc: "가까운 적을 향해 도토리를 발사합니다.",
    max: 8,
    stats: levels(
      { damage: 12, cooldown: 1.1, count: 1, pierce: 1, range: 480 },
      [
        { damage: 16 },
        { count: 2 },
        { cooldown: 0.9 },
        { pierce: 2 },
        { damage: 22 },
        { count: 3 },
        { cooldown: 0.75, pierce: 3 },
      ],
    ),
    up: [
      "",
      "피해 12 → 16",
      "탄환 1 → 2발",
      "공격 간격 1.1 → 0.9초",
      "탄환당 2명 관통",
      "피해 16 → 22",
      "부채꼴 탄환 3발",
      "공격 간격 0.75초 · 3명 관통",
    ],
  },
  {
    id: "tail",
    name: "꼬리 휩쓸기",
    glyph: "〰",
    color: "#e0a175",
    tag: "근접 · 밀쳐내기",
    desc: "가장 가까운 적을 꼬리로 쓸어냅니다.",
    max: 6,
    stats: levels(
      { damage: 18, cooldown: 2, range: 65, angle: 120, knockback: 24 },
      [
        { damage: 25 },
        { range: 80, angle: 160 },
        { cooldown: 1.6 },
        { double: true },
        { damage: 34, knockback: 40 },
      ],
    ),
    up: [
      "",
      "피해 18 → 25",
      "반경 80 · 공격각 160°",
      "공격 간격 2 → 1.6초",
      "앞뒤 양방향 휩쓸기",
      "피해 34 · 밀쳐내기 40",
    ],
  },
  {
    id: "stone",
    name: "조약돌 궤도",
    glyph: "◌",
    color: "#c2c6b5",
    tag: "회전 · 근접 방어",
    desc: "주위를 도는 돌이 다가오는 적을 막습니다.",
    max: 8,
    stats: levels(
      { damage: 10, count: 1, range: 55, speed: 120, cooldown: 0.5 },
      [
        { count: 2 },
        { damage: 14 },
        { speed: 160 },
        { count: 3 },
        { damage: 19 },
        { count: 4 },
        { double: true },
      ],
    ),
    up: [
      "",
      "회전 돌 2개",
      "피해 10 → 14",
      "회전 속도 증가",
      "회전 돌 3개",
      "피해 14 → 19",
      "회전 돌 4개",
      "안팎 이중 궤도",
    ],
  },
  {
    id: "vine",
    name: "덩굴 채찍",
    glyph: "⌁",
    color: "#a5ca6e",
    tag: "직선 · 관통",
    desc: "긴 덩굴로 일직선의 적을 타격합니다.",
    max: 7,
    stats: levels({ damage: 16, cooldown: 1.8, range: 150, width: 22 }, [
      { range: 190 },
      { damage: 23 },
      { cooldown: 1.4 },
      { double: true },
      { range: 230, width: 30 },
      { damage: 30, root: true },
    ]),
    up: [
      "",
      "길이 150 → 190",
      "피해 16 → 23",
      "공격 간격 1.8 → 1.4초",
      "교차 덩굴 추가",
      "길이 230 · 폭 30",
      "피해 30 · 끝부분 속박",
    ],
  },
  {
    id: "fire",
    name: "불씨 도토리",
    glyph: "♨",
    color: "#f29960",
    tag: "화염 · 지속 피해",
    desc: "착탄 지점에 적을 태우는 불길을 남깁니다.",
    max: 8,
    stats: levels(
      {
        damage: 20,
        cooldown: 2.4,
        count: 1,
        range: 400,
        radius: 35,
        duration: 2,
        tick: 3,
      },
      [
        { damage: 28 },
        { radius: 48 },
        { duration: 3, tick: 5 },
        { cooldown: 1.9 },
        { count: 2 },
        { damage: 36, radius: 60 },
        { burn: true },
      ],
    ),
    up: [
      "",
      "피해 20 → 28",
      "불길 반경 35 → 48",
      "불길 3초 · 지속 피해 증가",
      "공격 간격 2.4 → 1.9초",
      "불씨 2발",
      "피해 36 · 불길 반경 60",
      "화상 부여 · 처치 시 1회 전파",
    ],
  },
  {
    id: "lightning",
    name: "가지 번개",
    glyph: "ϟ",
    color: "#e7d889",
    tag: "연쇄 · 순간 타격",
    desc: "적 사이를 타고 흐르는 번개를 내립니다.",
    max: 8,
    stats: levels(
      { damage: 22, cooldown: 2.8, count: 2, range: 400, chain: 100 },
      [
        { count: 3 },
        { damage: 30 },
        { chain: 140 },
        { cooldown: 2.2 },
        { count: 5 },
        { damage: 40 },
        { count: 7, branch: true },
      ],
    ),
    up: [
      "",
      "연쇄 대상 3명",
      "피해 22 → 30",
      "연쇄 거리 100 → 140",
      "공격 간격 2.8 → 2.2초",
      "연쇄 대상 5명",
      "피해 30 → 40",
      "두 갈래 번개 · 최대 7명",
    ],
  },
  {
    id: "ice",
    name: "눈송이 고리",
    glyph: "❄",
    color: "#b3dbea",
    tag: "광역 · 감속",
    desc: "퍼져나가는 얼음 고리가 적을 늦춥니다.",
    max: 6,
    stats: levels(
      { damage: 10, cooldown: 3.2, range: 110, slow: 0.2, duration: 1.5 },
      [
        { range: 145 },
        { damage: 16 },
        { slow: 0.3, duration: 2 },
        { cooldown: 2.6 },
        { double: true },
      ],
    ),
    up: [
      "",
      "반경 110 → 145",
      "피해 10 → 16",
      "감속 30% · 지속 2초",
      "공격 간격 3.2 → 2.6초",
      "두 번째 얼음 고리",
    ],
  },
  {
    id: "bounce",
    name: "도토리 당구",
    glyph: "⤨",
    color: "#d2a56e",
    tag: "반사 · 폭발",
    desc: "적과 적 사이를 튕겨 다니는 도토리입니다.",
    max: 7,
    stats: levels({ damage: 14, cooldown: 2, count: 1, hits: 3, range: 420 }, [
      { damage: 20 },
      { hits: 4 },
      { cooldown: 1.6 },
      { count: 2 },
      { damage: 27, hits: 6 },
      { explode: true },
    ]),
    up: [
      "",
      "피해 14 → 20",
      "최대 명중 4회",
      "공격 간격 2 → 1.6초",
      "도토리 2발",
      "피해 27 · 최대 명중 6회",
      "마지막 명중에 폭발",
    ],
  },
  {
    id: "charm",
    name: "나무껍질 부적",
    glyph: "◇",
    color: "#dbc18a",
    tag: "보호 · 피해 차단",
    desc: "공격 대신 보호막으로 한 번의 피해를 막습니다.",
    max: 7,
    stats: levels({ count: 1, recharge: 20, invuln: 0.5 }, [
      { recharge: 18 },
      { count: 2 },
      { invuln: 0.7 },
      { recharge: 15 },
      { count: 3 },
      { recharge: 12 },
    ]),
    up: [
      "",
      "재충전 20 → 18초",
      "보호 최대 2회",
      "방어 후 무적 0.7초",
      "재충전 18 → 15초",
      "보호 최대 3회",
      "재충전 15 → 12초",
    ],
  },
  {
    id: "spore",
    name: "버섯 포자",
    glyph: "♧",
    color: "#cca5dc",
    tag: "이동 흔적 · 감속",
    desc: "지나온 자리에 포자 구름을 남깁니다.",
    max: 7,
    stats: levels({ distance: 90, radius: 30, duration: 3, tick: 5, cap: 6 }, [
      { tick: 8 },
      { radius: 42 },
      { distance: 70, cap: 8 },
      { duration: 4.5 },
      { tick: 12 },
      { slow: 0.2, radius: 50, cap: 10 },
    ]),
    up: [
      "",
      "지속 피해 5 → 8",
      "구름 반경 30 → 42",
      "이동 70마다 생성 · 최대 8개",
      "지속 3 → 4.5초",
      "지속 피해 8 → 12",
      "감속 구름 · 최대 10개",
    ],
  },
  {
    id: "bee",
    name: "벌떼 친구",
    glyph: "✤",
    color: "#e7ce6e",
    tag: "동료 · 추적",
    desc: "벌들이 적을 쏘고 다람이 곁으로 돌아옵니다.",
    max: 8,
    stats: levels(
      { damage: 14, count: 1, range: 300, speed: 260, cooldown: 1.8 },
      [
        { damage: 20 },
        { count: 2 },
        { cooldown: 1.4, speed: 320 },
        { count: 3 },
        { damage: 28, range: 380 },
        { count: 4 },
        { double: true },
      ],
    ),
    up: [
      "",
      "피해 14 → 20",
      "벌 2마리",
      "이동 속도 증가 · 대기 1.4초",
      "벌 3마리",
      "피해 28 · 탐색 거리 380",
      "벌 4마리",
      "출격당 서로 다른 적 2명 공격",
    ],
  },
  {
    id: "turret",
    name: "겨울 비축고",
    glyph: "⌂",
    color: "#d4b47f",
    tag: "설치 · 거점 사격",
    desc: "발밑에 도토리를 발사하는 비축고를 설치합니다.",
    max: 8,
    stats: levels(
      {
        damage: 10,
        interval: 8,
        count: 1,
        range: 360,
        cooldown: 1.2,
        duration: 12,
        shots: 1,
      },
      [
        { damage: 15 },
        { count: 2 },
        { duration: 18 },
        { range: 460, cooldown: 0.9 },
        { damage: 21 },
        { count: 3, interval: 6 },
        { shots: 2 },
      ],
    ),
    up: [
      "",
      "탄환 피해 10 → 15",
      "비축고 최대 2개",
      "지속 12 → 18초",
      "사거리 460 · 사격 간격 0.9초",
      "탄환 피해 15 → 21",
      "최대 3개 · 설치 간격 6초",
      "각 비축고에서 탄환 2발",
    ],
  },
  {
    id: "boomerang", name: "참나무 부메랑", glyph: "‹", color: "#e5b878",
    tag: "왕복 · 관통", desc: "앞으로 회전하며 날아갔다가 다람이에게 돌아옵니다. 왕복으로 적을 관통합니다.", max: 8,
    stats: levels({damage:18,cooldown:2.8,count:1,range:260,speed:310,radius:12,returnPower:1},[
      {damage:24},{range:320},{cooldown:2.3},{count:2},{damage:32},{radius:16},{cooldown:1.9,returnPower:1.3}
    ]),
    up: ["","피해 18 → 24","비행 거리 260 → 320","공격 간격 2.8 → 2.3초","부메랑 2개","피해 24 → 32","판정 반경 12 → 16","공격 간격 1.9초 · 돌아올 때 피해 +30%"],
  },
  {
    id: "seed", name: "바람개비 씨앗", glyph: "✣", color: "#c9db9b",
    tag: "나선 확산 · 감속", desc: "날개 달린 씨앗이 몸 중심에서 나선형으로 퍼집니다. 스친 적의 발걸음을 늦춥니다.", max: 8,
    stats: levels(
      { damage: 10, cooldown: 3.6, count: 3, range: 200, duration: 1.8, radius: 9, spin: 2.8, slow: 0.15, slowDuration: 0.8, alternate: false },
      [{damage:14}, {count:4}, {range:240}, {cooldown:3}, {count:5}, {damage:20}, {count:6, alternate:true, slow:0.25}],
    ),
    up: ["", "피해 10 → 14", "씨앗 3 → 4개", "확산 거리 200 → 240", "공격 간격 3.6 → 3초", "씨앗 4 → 5개", "피해 14 → 20", "씨앗 6개 · 회전 방향 교대 · 감속 25%"],
  },
];
export const BY_ID = Object.fromEntries(WEAPONS.map((w) => [w.id, w]));
export const PASSIVES = [
  {
    id: "might",
    name: "단단한 이빨",
    glyph: "✧",
    desc: "모든 무기 피해 +10%",
    max: 5,
  },
  {
    id: "haste",
    name: "가벼운 가지",
    glyph: "≋",
    desc: "공격 간격 −6% (부적·포자 제외)",
    max: 5,
  },
  { id: "speed", name: "가벼운 발", glyph: "»", desc: "이동 속도 +8%", max: 5 },
  {
    id: "health",
    name: "튼튼한 심장",
    glyph: "♡",
    desc: "최대 체력 +20 · 체력 20 회복",
    max: 5,
  },
  {
    id: "magnet",
    name: "숲의 주머니",
    glyph: "⊙",
    desc: "경험치 획득 반경 +24",
    max: 5,
  },
  {
    id: "area",
    name: "넓은 잎사귀",
    glyph: "♧",
    desc: "범위 무기 반경·길이 +10%",
    max: 5,
  },
];
export const ENEMIES = {
  snake: { hp: 18, speed: 38, damage: 8, r: 12, sprite: 6, xp: 2 },
  fox: { hp: 28, speed: 66, damage: 10, r: 13, sprite: 7, xp: 3 },
  mushroom: { hp: 55, speed: 29, damage: 12, r: 15, sprite: 8, xp: 4 },
  bat: { hp: 18, speed: 82, damage: 7, r: 11, sprite: 9, xp: 3 },
  boar: { hp: 110, speed: 36, damage: 18, r: 20, sprite: 10, xp: 8 },
  boss: { hp: 4800, speed: 35, damage: 24, r: 38, sprite: 11, xp: 0 },
};
export const xpRequired = (level) =>
  Math.round(7 + level * 3 + Math.pow(level, 1.34) * 1.4);
export const ending = [
  ['꿈 밖의 흔적', '곰은 서리가 남긴 그림자였나 봐. 사라지니 물길이 보이네.\n얼음 밑에 있던 이 매듭…… 엄마가 묶던 모양이야.'],
  ['익숙한 매듭', '영영 안 돌아오실 것만 같았는데…… 흔적이 여기 있었어.\n꿈속 목소리가 이 물길을 따라가라고 했던 걸까?'],
  ['다음 봄에는', '돌아오면 같이 잘 수 있게 자리를 비워 둘게.\n봄이 오면, 나도 물길을 건너 볼 거야.'],
];
